"""
AutoDev AI – Coding Agent
Generates complete source code for every file in the architecture.
"""

import asyncio
from agents import BaseAgent

FILE_SYSTEM = """You are an expert software developer.
Generate COMPLETE, PRODUCTION-QUALITY source code for the given file.
The code must be fully functional, well-commented, and follow best practices.
Return ONLY the raw source code — no markdown, no explanation, no backticks."""


class CodingAgent(BaseAgent):
    async def run(self, ctx: dict, emit) -> dict:
        plan = ctx.get("plan", {})
        arch = ctx.get("architecture", {})
        files_list = arch.get("files", [])
        generated = {}

        total = len(files_list)
        for i, filename in enumerate(files_list, 1):
            await emit("coder", f"Writing {filename}... ({i}/{total})")
            code = await self._generate_file(filename, ctx)
            generated[filename] = code
            progress = int((i / total) * 100)
            await asyncio.get_event_loop().run_in_executor(None, lambda: None)  # yield
            await self._queue_status(emit, progress)

        return generated

    async def _queue_status(self, emit, progress: int):
        await asyncio.sleep(0.2)

    async def _generate_file(self, filename: str, ctx: dict) -> str:
        plan = ctx.get("plan", {})
        arch = ctx.get("architecture", {})
        prompt_text = ctx.get("prompt", "")

        user_msg = f"""
Project request: {prompt_text}

Plan: {plan}

Full file list in project: {arch.get('files', [])}

Generate complete source code for: {filename}

Requirements:
- Language/Framework: {plan.get('language','python')}/{plan.get('framework','flask')}
- Database: {plan.get('database','none')}
- Auth required: {plan.get('auth_required', False)}
- Features: {plan.get('features', [])}

Write production-ready, complete code. No placeholders.
"""
        try:
            code = await asyncio.get_event_loop().run_in_executor(
                None,
                lambda: self._call_claude(FILE_SYSTEM, user_msg, max_tokens=3000)
            )
            # Strip markdown fences if LLM adds them
            if code.startswith("```"):
                lines = code.split("\n")
                code = "\n".join(lines[1:-1]) if lines[-1] == "```" else "\n".join(lines[1:])
            return code
        except Exception as e:
            return self._fallback_file(filename, plan, str(e))

    def _fallback_file(self, filename: str, plan: dict, error: str) -> str:
        fw = plan.get("framework", "flask")
        if filename == "app.py" and fw == "flask":
            return '''"""Flask Application"""
from flask import Flask, render_template, redirect, url_for
from flask_sqlalchemy import SQLAlchemy

app = Flask(__name__)
app.config["SECRET_KEY"] = "change-me-in-production"
app.config["SQLALCHEMY_DATABASE_URI"] = "sqlite:///app.db"
db = SQLAlchemy(app)


@app.route("/")
def index():
    return render_template("index.html")


if __name__ == "__main__":
    with app.app_context():
        db.create_all()
    app.run(debug=True)
'''
        if filename == "requirements.txt":
            return "flask\nflask-sqlalchemy\nflask-login\n"
        if filename == "README.md":
            return f"# {plan.get('summary','Project')}\n\nGenerated by AutoDev AI.\n\n## Run\n```\npip install -r requirements.txt\npython app.py\n```\n"
        if filename.endswith(".html"):
            return """<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><title>App</title></head>
<body>
  <h1>Welcome</h1>
  <p>Generated by AutoDev AI</p>
</body>
</html>"""
        return f"# {filename}\n# Generated by AutoDev AI\n# Note: {error}\n"
