"""
AutoDev AI – Packaging Agent
Ensures all packaging files exist (requirements.txt, README, .gitignore, etc.)
and adds any missing boilerplate.
"""

import asyncio
from agents import BaseAgent

README_SYSTEM = """You are a technical writer. Write a complete, professional README.md
for the given project. Include: title, description, features, installation, usage, and license.
Return ONLY the markdown content."""


class PackagingAgent(BaseAgent):
    async def run(self, ctx: dict, emit) -> dict:
        files = dict(ctx.get("generated_files", {}))
        plan = ctx.get("plan", {})
        prompt = ctx.get("prompt", "")

        await emit("packager", "Verifying project package completeness...")

        # Ensure .gitignore
        if ".gitignore" not in files:
            files[".gitignore"] = self._gitignore(plan)
            await emit("packager", "  📄 Added .gitignore")

        # Ensure requirements.txt has content
        if "requirements.txt" not in files or not files["requirements.txt"].strip():
            files["requirements.txt"] = self._requirements(plan)
            await emit("packager", "  📄 Generated requirements.txt")

        # Ensure README.md
        if "README.md" not in files or len(files.get("README.md", "")) < 100:
            await emit("packager", "  📝 Writing README.md...")
            try:
                readme = await asyncio.get_event_loop().run_in_executor(
                    None,
                    lambda: self._call_claude(
                        README_SYSTEM,
                        f"Project: {prompt}\nPlan: {plan}",
                        max_tokens=1500,
                    )
                )
                files["README.md"] = readme
            except Exception:
                files["README.md"] = self._fallback_readme(plan, prompt)

        # Add .env.example if needed
        if plan.get("auth_required") and ".env.example" not in files:
            files[".env.example"] = "SECRET_KEY=your-secret-key-here\nDATABASE_URL=sqlite:///app.db\n"
            await emit("packager", "  📄 Added .env.example")

        await emit("packager", f"  ✅ Package complete — {len(files)} files total")
        return files

    def _gitignore(self, plan: dict) -> str:
        lang = plan.get("language", "python")
        base = "__pycache__/\n*.pyc\n*.pyo\n.env\n.venv\nvenv/\n*.egg-info/\ndist/\nbuild/\n*.db\n"
        if lang == "javascript":
            base += "node_modules/\n.next/\ndist/\n"
        return base

    def _requirements(self, plan: dict) -> str:
        fw = plan.get("framework", "flask")
        db = plan.get("database", "none")
        auth = plan.get("auth_required", False)
        pkgs = []
        if fw == "flask":
            pkgs += ["flask>=3.0.0", "flask-sqlalchemy>=3.0.0"]
            if auth:
                pkgs += ["flask-login>=0.6.0", "flask-wtf>=1.2.0", "werkzeug>=3.0.0"]
        elif fw in ("fastapi", "fastapi "):
            pkgs += ["fastapi>=0.110.0", "uvicorn>=0.29.0", "sqlalchemy>=2.0.0"]
            if auth:
                pkgs += ["python-jose>=3.3.0", "passlib>=1.7.4"]
        elif fw == "django":
            pkgs += ["django>=5.0"]
        else:
            pkgs += ["flask>=3.0.0"]
        if db == "sqlite":
            pass  # built-in
        elif db == "postgres":
            pkgs.append("psycopg2-binary>=2.9.0")
        return "\n".join(pkgs) + "\n"

    def _fallback_readme(self, plan: dict, prompt: str) -> str:
        name = plan.get("summary", prompt[:40])
        fw = plan.get("framework", "python")
        return f"""# {name}

> Generated by AutoDev AI

## Description
{prompt}

## Tech Stack
- Language: {plan.get('language','Python')}
- Framework: {plan.get('framework','Flask')}
- Database: {plan.get('database','SQLite')}

## Installation
```bash
pip install -r requirements.txt
```

## Running
```bash
python app.py
```

## License
MIT
"""
